[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && daphne -b 0.0.0.0 -p $PORT TaskForge.asgi:application"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
